# Generated by Django 5.2.1 on 2025-05-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='organization',
            new_name='inn',
        ),
    ]
